### ISSUE TITLE
Exploratory and expository figures for FISH 549 assignment 5

### ISSUE THREAD

**Issue by arhennings** [arhennings/FISH549_Assignment-5#1]
I created a basic research compendium and added the data and Rmd to the data and figures folders, respectively. I subsequently cleaned the data a bit, made a few basic exploratory figures, and made a single combination expository violin plot. The figures were not exported and saved separately.

**Comment by mdscheuerell** [comment]
Nice job with your figures, Andrea, although I had to knit your `.Rmd` file to create the plots. And before doing so, I had to change the location of the data folder from within (ie, the call to `here()` wasn't pointing to the proper folder structure).
